# This is the name that appears in GitHub's Actions tab
name: Update Terraform Documentation

# When should this run?
on:
  push:
    # Only run when .tf files change
    paths:
      - 'modules/**/*.tf'
    # Only run on main branch
    branches: [main]

# What should it do?
jobs:
  update-docs:
    # Run on GitHub's Ubuntu servers
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Download your repo to GitHub's server
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This gives the action permission to push back
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Step 2: Install terraform-docs
      - name: Install terraform-docs
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/
      
      # Step 3: Generate documentation
      - name: Generate documentation
        run: |
          cd modules/s3-bucket
          terraform-docs .
      
      # Step 4: Commit changes if any
      - name: Commit documentation changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # Only commit if there are changes
          git diff --staged --quiet || git commit -m "docs: auto-update terraform documentation [skip ci]"
          git push